name: "Action 1"
description: "The First Action"
inputs:
  name:
    description: 'Your name'
    required: true
outputs:
  time: # id of output
    value: ${{ steps.random-number-generator.outputs.random-number }}
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - name: Set env variables
      run: |
        echo "TRUE_ENV_VARIABLE=true" >> $GITHUB_ENV
        echo "FALSE_ENV_VARIABLE=false" >> $GITHUB_ENV
      shell: bash
    - if: env.TRUE_ENV_VARIABLE == 'true'
      run: echo 'TRUE_ENV_VARIABLE is true'
      shell: bash
    - if: env.FALSE_ENV_VARIABLE == 'true'
      # not supposed to run
      run: echo 'FALSE_ENV_VARIABLE is also true (Surprise!)'
      shell: bash
    - if: inputs.name == 'John'
      run: echo Hello John -> ${{ inputs.name }}.
      shell: bash
    - if: inputs.name != 'John'
      run: echo Hello !John -> ${{ inputs.name }}.
      shell: bash
    - run: |
        echo "Nice to meet you! ${{ env.SOME_ENV }}"
        echo "Nice to meet you! ${MY_VAR}"
      shell: bash
      env:
        MY_VAR: ${{ inputs.name }}
    - id: random-number-generator
      run: echo "::set-output name=random-number::$(echo $RANDOM)"
      shell: bash