on:
  workflow_call:
    inputs:
      FILTERS:
        required: false
        type: string

env:
  ENV_FILTER: ${{ inputs.FILTERS }}

jobs:
  template:
    strategy:
      max-parallel: 5
      matrix:
#        filter: ${{ fromJSON(env.ENV_FILTER) }} - that won't work as matrix has no access to env context https://github.com/actions/runner/issues/480
        filter: ${{ fromJSON(inputs.FILTERS) }}
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable
        run: echo "FILTER=${{ matrix.filter }}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Echo
        run: |
          echo "Matrix FILTER is ${{ matrix.filter }}"
          echo "env.FILTER is $FILTER"
          echo "env.ENV_FILTER is $ENV_FILTER"