on:
  workflow_call:
    inputs:
      ENV_VARIABLE:
        type: string
      OTHER_ENV_VARIABLE:
        type: string

env:
  ENV_VARIABLE: ${{ inputs.ENV_VARIABLE }}

jobs:
  template:
    strategy:
      max-parallel: 1
      matrix:
        MATRIX_VALUE:
          - value-1
          - 'value 2'
          - "value 3"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: |
          echo 'MATRIX_VALUE is ${{ matrix.MATRIX_VALUE }}'
          echo "[INPUT] $ENV_VARIABLE"
          echo "[INPUT] ${{ inputs.ENV_VARIABLE }}"
          echo "[INPUT] ${{ inputs.OTHER_ENV_VARIABLE }}"
          echo "inherited ${{ secrets.SUPER_SECRET }}"