name: "template"

on:
  workflow_call:
    inputs:
      ENV_VARIABLE:
        type: string
      OTHER_ENV_VARIABLE:
        type: string
    secrets:
      ALL_SECRETS:

env:
  ENV_VARIABLE: ${{ inputs.ENV_VARIABLE }}
  SUPER_SECRET: ${{ fromJSON(secrets.ALL_SECRETS).SUPER_SECRET }}

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: |
          echo "[INPUT] $ENV_VARIABLE"
          echo "[INPUT] ${{ inputs.ENV_VARIABLE }}"
          echo "[INPUT] ${{ inputs.OTHER_ENV_VARIABLE }}"
          echo '${{ fromJSON(secrets.ALL_SECRETS).SUPER_SECRET }}'
          echo $SUPER_SECRET