name: "template"

on:
  workflow_call:
    inputs:
      INPUT:
        type: string
    secrets:
      SECRET:
        required: false

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: |
          echo "[INPUT] ${{ inputs.INPUT }}"
          echo "[SECRET] ${{ secrets.SECRET }}"
          echo "[TEMPLATE] $SOME_VARIABLE"
          echo "[TEMPLATE] $STRING_INPUT"
          echo "[TEMPLATE] ${{ secrets.SUPER_SECRET }}"
          echo "[TEMPLATE] ${{ secrets }}"