on:
  workflow_call:
    inputs:
      ENV_VARIABLE:
        type: string
      OTHER_ENV_VARIABLE:
        type: string
      CONTAINS_DEMO_1:
        type: boolean
        required: false
        description: 'Should be boolean'
        default: false
      CONTAINS_DEMO_2:
        type: boolean

env:
  ENV_VARIABLE: ${{ inputs.ENV_VARIABLE }}

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: |
          echo "[INPUT] $ENV_VARIABLE"
          echo "[CONTAINS item1] ${{ inputs.CONTAINS_DEMO_1 }}"
          echo "[CONTAINS item123] ${{ inputs.CONTAINS_DEMO_2 }}"
          echo "[INPUT] ${{ inputs.ENV_VARIABLE }}"
          echo "[INPUT] ${{ inputs.OTHER_ENV_VARIABLE }}"
          echo "inherited ${{ secrets.SUPER_SECRET }}"